version: "3"

networks:
  gitea:
    external: true

services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${giteaDBPort}
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${giteaDBUserName}
      - GITEA__database__PASSWD=${giteaDBUserPass}
    restart: always
    networks:
      - gitea
    volumes:
      - /opt/gitea/gitea:/data:Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${giteaDBUserName}
      - POSTGRES_PASSWORD=${giteaDBUserPass}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - /opt/gitea/postgres:/var/lib/postgresql/data:Z

  runner:
    image: gitea/act_runner:nightly
    environment:
      CONFIG_FILE: /config/config.yaml
      GITEA_INSTANCE_URL: "${INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "${RUNNER_NAME}"
      # GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
    depends_on:
      - server
      - db
    networks:
      - gitea
    volumes:
      - /opt/gitea/runner/config/:/config:Z
      - /opt/gitea/runner/data:/data:Z
      - /var/run/docker.sock:/var/run/docker.sock