version: "3"

networks:
  gitea:
    external: true

services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${giteaDBPort}
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${giteaDBUserName}
      - GITEA__database__PASSWD=${giteaDBUserPass}
    restart: always
    networks:
      - gitea
    volumes:
      - /data/gitea/persistent_data/gitea:/data:Z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${giteaDBUserName}
      - POSTGRES_PASSWORD=${giteaDBUserPass}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - /data/gitea/persistent_data/postgres:/var/lib/postgresql/data:Z