---

version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Copenhagen    # optional: set desired timezone
    user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - /opt/dockermnts/ntfy/cache:/var/cache/ntfy
      - /opt/dockermnts/ntfy/config:/etc/ntfy
    ports:
      - 8060:80
    restart: unless-stopped